version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST= mysql
      - DB_USER= root
      - DB_PASSWORD= 120202
      - DB_NAME= cursos_db
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 120202
      MYSQL_DATABASE: cursos_db
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
